# Numpy Vectorisation 

## Importing Requirements

In [1]:
import numpy as np
import time

## Numpy Arrays

Numpy arrays are 1-d arrays, with shape (n,): n elements indexed [0] through to [n-1]

### Vector Creation

In [5]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.03855963 0.49568668 0.50734693 0.9387221 ], a shape = (4,), a data type = float64


Some data creation routines do not take a shape tuple

In [6]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [1.45485999e-01 4.50767082e-04 3.96464881e-01 6.76041565e-01], a shape = (4,), a data type = float64


**Routines that accept a shape tuple:**
- `np.zeros(4)` or `np.zeros((4,))` — both work
- `np.random.random_sample(4)` — accepts a shape tuple

**Routines that don't accept a shape tuple:**
- `np.arange(4.)` — takes individual arguments (start, stop, step), not a shape tuple
- `np.random.rand(4)` — takes dimensions as separate arguments, not a tuple

So you can't do:
- `np.arange((4,))` ❌
- `np.random.rand((4,))` ❌

Instead, you pass the dimensions directly:
- `np.arange(4.)` ✅
- `np.random.rand(4)` ✅

The difference: some routines use a shape tuple `(4,)`, while others take dimensions as separate arguments. This is a NumPy API design difference between routines.

In [7]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


These have all created a one-dimensional vector  `a` with four elements. `a.shape` returns the dimensions. Here we see a.shape = `(4,)` indicating a 1-d array with 4 elements.  

### Operations on Vectors

We can access elements of vectors by indexing or slicing. 

- Indexing means referring to an element of the array by its relative position within the array
- Slicing means getting a subset of the elements from the array based on their indices 

Indexing

In [14]:
# vector indexing on a 1-d vector
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
# Accessing elements of a vector
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# Accessing the last element, negatice indexes count from the end
print(f"a[-1] = {a[-1]}")

a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9


In [16]:
#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid.

In [17]:
# Vector silicing
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
# access all elements
c = a[:]
print(f"a[:] = {c}")

# access 5 consecutive elements 
c = a [2:7:1]
print(f"a[2:7:1] = {c}")


# access 3 elements at intervals of 2
c = a[2:7:2]
print(f"a[2:7:2] = {c}")

# access all elements except the first 3
c = a[3:]
print(f"a[3:] = {c}")       

# access all elements except the last 3
c = a[:3]
print(f"a[:3] = {c}")



a[:] = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] = [2 3 4 5 6]
a[2:7:2] = [2 4 6]
a[3:] = [3 4 5 6 7 8 9]
a[:3] = [0 1 2]


### Single Vector Operations

In [24]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


### Vector on Vector element-wise operations



In [25]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


For this to work correctly, both the vectors must be the same size,m otherwise an error will be raised

In [26]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


### Scalar Vector Operations

Vectors can be scaled by scalar values, the scalar essetnially multiplies all of the elements inside a specific vector.

In [27]:
a = np.array([1,2,3,4])

# multiply a by a scalar
b = 5 * a
print(f"b = 5 * a : {b}")

# divide a by a scalar
c = a / 2
print(f"c = a / 2 : {c}")


b = 5 * a : [ 5 10 15 20]
c = a / 2 : [0.5 1.  1.5 2. ]


## Vector Dot Product

The dot product multiplies the values in two vectors element-wise and then sums the result.
Vector dot product requires the dimensions of the two vectors to be the same. 

We can implement our own version of the dot product below:

**Using a for loop**, implement a function which returns the dot product of two vectors. The function to return given inputs $a$ and $b$:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Assume both `a` and `b` are the same shape.

In [28]:
def dot_product(a, b):
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """

    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [38]:
# testing the function
a = np.array([1, 2, 3, 4])
b = np.array([-1, 5, 3, 2])
print(f"dot_product(a, b) = {dot_product(a, b)}")

dot_product(a, b) = 26


We got the scalar value, but we can try the same operation using  `np.dot`

In [39]:

c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 

c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 26, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 26, np.dot(a, b).shape = () 


### Performance Comparison

In [41]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = dot_product(a,b)
toc = time.time()  # capture end time

print(f"dot_product(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 2.0962 ms 
dot_product(a, b) =  2501072.5817
loop version duration: 888.5653 ms 


Vectorization provides a large speed up in this example. This is because NumPy makes better use of available data parallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in Machine Learning where the data sets are often very large.

## Matrices

Aligning and understanding the shapes of the operands is important when performing vector operations, especially as they get bigger.

Matrices, are two dimensional arrays. The elements of a matrix are all of the same type. In notation, matrices are denoted with capitol, bold letter such as $\mathbf{X}$. In this and other labs, `m` is often the number of rows and `n` the number of columns. The elements of a matrix can be referenced with a two dimensional index. In math settings, numbers in the index typically run from 1 to n. In computer science and these labs, indexing will run from 0 to n-1.

In [42]:
# common example
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


2-D matrices are used to hold training data. Training data is $m$ examples by $n$ features creating an (m,n) array. Course 1 does not do operations directly on matrices but typically extracts an example as a vector and operates on that. Below you will review: 
- data creation
- slicing and indexing

### Matrix creation

In [43]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


One can also manually specify data. Dimensions are specified with additional brackets matching the format in the printing above.

In [44]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


### Operations on matrices

Matrices include a second index. The two indexes describe [row, column]. Access can either return an element or a row/column. See below:

In [45]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


**Reshape**  
The previous example used [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) to shape the array.  
`a = np.arange(6).reshape(-1, 2) `   
This line of code first created a *1-D Vector* of six elements. It then reshaped that vector into a *2-D* array using the reshape command. This could have been written:  
`a = np.arange(6).reshape(3, 2) `  
To arrive at the same 3 row, 2 column array.
The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.


Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid.

In [ ]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10) # only -1 is documented to auto-calculate a dimension so that one does not need to be changed
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
